version: '3'

services:
  db:
    image: postgres:16-alpine
    container_name: postgres_pta
    ports:
      - 5433:5432
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'smart_home'
volumes:
  db-store: